baseurl = "https://crazyoptimist.net/"
# relativeurls = true
title = "crazyoptimist"
author = "crazyoptimist"

# canonifyurls = true
paginate = 10
disqusShortname = "crazy-optimist"

# Install theme as a hugo module
[module]
[[module.imports]]
  path = "github.com/chipzoller/hugo-clarity"


[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
