[[main]]
  name = "About"
  url = "about/"
  weight = 1

[[main]]
  name = "Posts"
  url = "posts/"
  weight = 1

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/crazyoptimist"
[[social]]
  name = "mail"
  weight = 2
  url = "mailto:hey@crazyoptimist.net"
[[social]]
  name = "rss"
  weight = 3
  url = "index.xml"
