[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.75.1"
  HUGO_ENV = "production hugo --gc --minify"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.75.1"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.75.1"

