version: 2.1
orbs:
  firebase-deploy: azdevs/firebase-deploy@1.0.0
  hugo: circleci/hugo@1.0.0

jobs:
  build:
    executor:
      name: hugo/build
    steps:
      - checkout
      - run:
          command:
              pwd && echo "heeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeey"
      - hugo/install:
          version: 0.75.1
      - hugo/hugo-build:
          extra-flags: '--gc --minify'
      - persist_to_workspace:
          root: ~/project
          paths:
            - public
            - resources

  deploy:
    docker:
      - image: 'circleci/node:lts'
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - firebase-deploy/deploy:
          token: '$FIREBASE_TOKEN'
          alias: 'crazyoptimist-net'
workflows:
  build-and-deploy:
    jobs:
      - deploy:
          requires:
            - build
