name: GitHub Pages

on:
  push:
    branches:
      - main
      - ci/gha-migration
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.122.0'
          extended: true

      - name: Install Hugo Modules
        run: hugo mod tidy

      - name: Build
        run: hugo --gc --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/ci/gha-migration'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
